package Root1.impl;

import Root1.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMedium <br>
 * @version generated on Wed Apr 28 11:02:02 IST 2021 by prateksha
 */
public class DefaultMedium extends WrappedIndividualImpl implements Medium {

    public DefaultMedium(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
