package ProtegeGenCode.Root2;

import ProtegeGenCode.Root2.impl.*;


import java.util.Collection;

import org.protege.owl.codegeneration.CodeGenerationFactory;
import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.FactoryHelper;
import org.protege.owl.codegeneration.impl.ProtegeJavaMapping;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.protege.owl.codegeneration.inference.SimpleInference;

import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

/**
 * A class that serves as the entry point to the generated code providing access
 * to existing individuals in the ontology and the ability to create new individuals in the ontology.<p>
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: Root2<br>
 * @version generated on Sun May 16 23:25:38 IST 2021 by gurleen
 */
public class Root2 implements CodeGenerationFactory {
    private OWLOntology ontology;
    private ProtegeJavaMapping javaMapping = new ProtegeJavaMapping();
    private FactoryHelper delegate;
    private CodeGenerationInference inference;

    public Root2(OWLOntology ontology) {
	    this(ontology, new SimpleInference(ontology));
    }
    
    public Root2(OWLOntology ontology, CodeGenerationInference inference) {
        this.ontology = ontology;
        this.inference = inference;
        javaMapping.initialize(ontology, inference);
        delegate = new FactoryHelper(ontology, inference);
    }

    public OWLOntology getOwlOntology() {
        return ontology;
    }
    
    public void saveOwlOntology() throws OWLOntologyStorageException {
        ontology.getOWLOntologyManager().saveOntology(ontology);
    }
    
    public void flushOwlReasoner() {
        delegate.flushOwlReasoner();
    }
    
    public boolean canAs(WrappedIndividual resource, Class<? extends WrappedIndividual> javaInterface) {
    	return javaMapping.canAs(resource, javaInterface);
    }
    
    public  <X extends WrappedIndividual> X as(WrappedIndividual resource, Class<? extends X> javaInterface) {
    	return javaMapping.as(resource, javaInterface);
    }
    
    public Class<?> getJavaInterfaceFromOwlClass(OWLClass cls) {
        return javaMapping.getJavaInterfaceFromOwlClass(cls);
    }
    
    public OWLClass getOwlClassFromJavaInterface(Class<?> javaInterface) {
	    return javaMapping.getOwlClassFromJavaInterface(javaInterface);
    }
    
    public CodeGenerationInference getInference() {
        return inference;
    }

    /* ***************************************************
     * Class http://www.semanticweb.org/gurleen/ontologies/people#adults
     */

    {
        javaMapping.add("http://www.semanticweb.org/gurleen/ontologies/people#adults", Adults.class, DefaultAdults.class);
    }

    /**
     * Creates an instance of type Adults.  Modifies the underlying ontology.
     */
    public Adults createAdults(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_ADULTS, DefaultAdults.class);
    }

    /**
     * Gets an instance of type Adults with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Adults getAdults(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_ADULTS, DefaultAdults.class);
    }

    /**
     * Gets all instances of Adults from the ontology.
     */
    public Collection<? extends Adults> getAllAdultsInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_ADULTS, DefaultAdults.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/gurleen/ontologies/people#old
     */

    {
        javaMapping.add("http://www.semanticweb.org/gurleen/ontologies/people#old", Old.class, DefaultOld.class);
    }

    /**
     * Creates an instance of type Old.  Modifies the underlying ontology.
     */
    public Old createOld(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_OLD, DefaultOld.class);
    }

    /**
     * Gets an instance of type Old with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Old getOld(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_OLD, DefaultOld.class);
    }

    /**
     * Gets all instances of Old from the ontology.
     */
    public Collection<? extends Old> getAllOldInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_OLD, DefaultOld.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/gurleen/ontologies/people#people
     */

    {
        javaMapping.add("http://www.semanticweb.org/gurleen/ontologies/people#people", People.class, DefaultPeople.class);
    }

    /**
     * Creates an instance of type People.  Modifies the underlying ontology.
     */
    public People createPeople(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_PEOPLE, DefaultPeople.class);
    }

    /**
     * Gets an instance of type People with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public People getPeople(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_PEOPLE, DefaultPeople.class);
    }

    /**
     * Gets all instances of People from the ontology.
     */
    public Collection<? extends People> getAllPeopleInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_PEOPLE, DefaultPeople.class);
    }


    /* ***************************************************
     * Class http://www.semanticweb.org/gurleen/ontologies/people#young
     */

    {
        javaMapping.add("http://www.semanticweb.org/gurleen/ontologies/people#young", Young.class, DefaultYoung.class);
    }

    /**
     * Creates an instance of type Young.  Modifies the underlying ontology.
     */
    public Young createYoung(String name) {
		return delegate.createWrappedIndividual(name, Vocabulary.CLASS_YOUNG, DefaultYoung.class);
    }

    /**
     * Gets an instance of type Young with the given name.  Does not modify the underlying ontology.
     * @param name the name of the OWL named individual to be retrieved.
     */
    public Young getYoung(String name) {
		return delegate.getWrappedIndividual(name, Vocabulary.CLASS_YOUNG, DefaultYoung.class);
    }

    /**
     * Gets all instances of Young from the ontology.
     */
    public Collection<? extends Young> getAllYoungInstances() {
		return delegate.getWrappedIndividuals(Vocabulary.CLASS_YOUNG, DefaultYoung.class);
    }


}
