package ProtegeGenCode.Root2;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon May 17 15:08:03 IST 2021 by gurleen
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/gurleen/ontologies/people#people
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PEOPLE.<p>
     * 
     */
    public static final OWLClass CLASS_PEOPLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#people"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gurleen/ontologies/people#hasAncestor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASANCESTOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASANCESTOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#hasAncestor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gurleen/ontologies/people#hasChild
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHILD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHILD = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#hasChild"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gurleen/ontologies/people#hasFather
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFATHER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFATHER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#hasFather"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gurleen/ontologies/people#hasFriend
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFRIEND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFRIEND = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#hasFriend"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/gurleen/ontologies/people#hasMother
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMOTHER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMOTHER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/gurleen/ontologies/people#hasMother"));


}
