package ProtegeGenCode.Root1;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: DeepPanBase <br>
 * @version generated on Wed Apr 28 11:02:02 IST 2021 by prateksha
 */

public interface DeepPanBase extends PizzaBase {

    /* ***************************************************
     * Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasIngredient
     */
     
    /**
     * Gets all property values for the hasIngredient property.<p>
     * 
     * @returns a collection of values for the hasIngredient property.
     */
    Collection<? extends Food> getHasIngredient();

    /**
     * Checks if the class has a hasIngredient property value.<p>
     * 
     * @return true if there is a hasIngredient property value.
     */
    boolean hasHasIngredient();

    /**
     * Adds a hasIngredient property value.<p>
     * 
     * @param newHasIngredient the hasIngredient property value to be added
     */
    void addHasIngredient(Food newHasIngredient);

    /**
     * Removes a hasIngredient property value.<p>
     * 
     * @param oldHasIngredient the hasIngredient property value to be removed.
     */
    void removeHasIngredient(Food oldHasIngredient);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
