package ProtegeGenCode.Root1;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Apr 28 11:02:02 IST 2021 by prateksha
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#American
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AMERICAN.<p>
     * 
     */
    public static final OWLClass CLASS_AMERICAN = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#American"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#AmericanHot
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AMERICANHOT.<p>
     * 
     */
    public static final OWLClass CLASS_AMERICANHOT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#AmericanHot"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#AnchoviesTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANCHOVIESTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ANCHOVIESTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#AnchoviesTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ArtichokeTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTICHOKETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ARTICHOKETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ArtichokeTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#AsparagusTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASPARAGUSTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ASPARAGUSTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#AsparagusTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Cajun
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAJUN.<p>
     * 
     */
    public static final OWLClass CLASS_CAJUN = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Cajun"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#CajunSpiceTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAJUNSPICETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_CAJUNSPICETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#CajunSpiceTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#CaperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_CAPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#CaperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Capricciosa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAPRICCIOSA.<p>
     * 
     */
    public static final OWLClass CLASS_CAPRICCIOSA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Capricciosa"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Caprina
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAPRINA.<p>
     * 
     */
    public static final OWLClass CLASS_CAPRINA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Caprina"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHEESETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_CHEESETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHEESYPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_CHEESYPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHEESYVEGETABLETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_CHEESYVEGETABLETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ChickenTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHICKENTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_CHICKENTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ChickenTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Country
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COUNTRY.<p>
     * 
     */
    public static final OWLClass CLASS_COUNTRY = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Country"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#DeepPanBase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEEPPANBASE.<p>
     * 
     */
    public static final OWLClass CLASS_DEEPPANBASE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#DeepPanBase"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#DomainConcept
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOMAINTHING.<p>
     * 
     */
    public static final OWLClass CLASS_DOMAINTHING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#DomainConcept"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Fiorentina
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FIORENTINA.<p>
     * 
     */
    public static final OWLClass CLASS_FIORENTINA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Fiorentina"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#FishTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEAFOODTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SEAFOODTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#FishTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Food
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FOOD.<p>
     * 
     */
    public static final OWLClass CLASS_FOOD = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Food"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#FourCheesesTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FOURCHEESESTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_FOURCHEESESTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#FourCheesesTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#FourSeasons
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FOURSEASONS.<p>
     * 
     */
    public static final OWLClass CLASS_FOURSEASONS = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#FourSeasons"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#FruitTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRUITTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_FRUITTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#FruitTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#FruttiDiMare
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRUTTIDIMARE.<p>
     * 
     */
    public static final OWLClass CLASS_FRUTTIDIMARE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#FruttiDiMare"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#GarlicTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GARLICTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_GARLICTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#GarlicTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Giardiniera
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GIARDINIERA.<p>
     * 
     */
    public static final OWLClass CLASS_GIARDINIERA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Giardiniera"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#GoatsCheeseTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GOATSCHEESETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_GOATSCHEESETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#GoatsCheeseTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#GorgonzolaTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GORGONZOLATOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_GORGONZOLATOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#GorgonzolaTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#GreenPepperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GREENPEPPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_GREENPEPPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#GreenPepperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#HamTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAMTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_HAMTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#HamTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#HerbSpiceTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HERBSPICETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_HERBSPICETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#HerbSpiceTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Hot
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOT.<p>
     * 
     */
    public static final OWLClass CLASS_HOT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Hot"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#HotGreenPepperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTGREENPEPPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_HOTGREENPEPPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#HotGreenPepperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#HotSpicedBeefTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTSPICEDBEEFTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_HOTSPICEDBEEFTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#HotSpicedBeefTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ICECREAM.<p>
     * 
     */
    public static final OWLClass CLASS_ICECREAM = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#InterestingPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTERESTINGPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_INTERESTINGPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#InterestingPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#JalapenoPepperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class JALAPENOPEPPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_JALAPENOPEPPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#JalapenoPepperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#LaReine
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LAREINE.<p>
     * 
     */
    public static final OWLClass CLASS_LAREINE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#LaReine"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#LeekTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEEKTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_LEEKTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#LeekTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Margherita
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MARGHERITA.<p>
     * 
     */
    public static final OWLClass CLASS_MARGHERITA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Margherita"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#MeatTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEATTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_MEATTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#MeatTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#MeatyPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEATYPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_MEATYPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#MeatyPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Medium
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDIUM.<p>
     * 
     */
    public static final OWLClass CLASS_MEDIUM = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Medium"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Mild
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MILD.<p>
     * 
     */
    public static final OWLClass CLASS_MILD = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Mild"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#MixedSeafoodTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIXEDSEAFOODTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_MIXEDSEAFOODTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#MixedSeafoodTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#MozzarellaTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOZZARELLATOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_MOZZARELLATOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#MozzarellaTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Mushroom
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MUSHROOM.<p>
     * 
     */
    public static final OWLClass CLASS_MUSHROOM = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Mushroom"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#MushroomTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MUSHROOMTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_MUSHROOMTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#MushroomTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#NamedPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NAMEDPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_NAMEDPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#NamedPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Napoletana
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NAPOLETANA.<p>
     * 
     */
    public static final OWLClass CLASS_NAPOLETANA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Napoletana"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#NonVegetarianPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONVEGETARIANPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_NONVEGETARIANPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#NonVegetarianPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#NutTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NUTTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_NUTTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#NutTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#OliveTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OLIVETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_OLIVETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#OliveTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#OnionTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONIONTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ONIONTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#OnionTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ParmaHamTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARMAHAMTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PARMAHAMTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ParmaHamTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Parmense
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARMENSE.<p>
     * 
     */
    public static final OWLClass CLASS_PARMENSE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Parmense"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ParmesanTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARMEZANTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PARMEZANTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ParmesanTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PeperonataTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PEPERONATATOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PEPERONATATOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PeperonataTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PeperoniSausageTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PEPERONISAUSAGETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PEPERONISAUSAGETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PeperoniSausageTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PepperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PEPPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PEPPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PepperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PetitPoisTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PETITPOISTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PETITPOISTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PetitPoisTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PineKernels
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PINEKERNELTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PINEKERNELTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PineKernels"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Pizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_PIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Pizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PizzaBase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIZZABASE.<p>
     * 
     */
    public static final OWLClass CLASS_PIZZABASE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PizzaBase"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PizzaTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIZZATOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PIZZATOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PizzaTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PolloAdAstra
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class POLLOADASTRA.<p>
     * 
     */
    public static final OWLClass CLASS_POLLOADASTRA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PolloAdAstra"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PrawnsTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRAWNSTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_PRAWNSTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PrawnsTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#PrinceCarlo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRINCECARLO.<p>
     * 
     */
    public static final OWLClass CLASS_PRINCECARLO = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#PrinceCarlo"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#QuattroFormaggi
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUATTROFORMAGGI.<p>
     * 
     */
    public static final OWLClass CLASS_QUATTROFORMAGGI = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#QuattroFormaggi"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#RealItalianPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REALITALIANPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_REALITALIANPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#RealItalianPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#RedOnionTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REDONIONTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_REDONIONTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#RedOnionTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#RocketTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROCKETTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ROCKETTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#RocketTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Rosa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROSA.<p>
     * 
     */
    public static final OWLClass CLASS_ROSA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Rosa"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#RosemaryTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROSEMARYTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_ROSEMARYTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#RosemaryTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SauceTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SAUCETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SAUCETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SauceTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Siciliana
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SICILIANA.<p>
     * 
     */
    public static final OWLClass CLASS_SICILIANA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Siciliana"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SlicedTomatoTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SLICEDTOMATOTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SLICEDTOMATOTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SlicedTomatoTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SloppyGiuseppe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SLOPPYGIUSEPPE.<p>
     * 
     */
    public static final OWLClass CLASS_SLOPPYGIUSEPPE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SloppyGiuseppe"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Soho
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOHO.<p>
     * 
     */
    public static final OWLClass CLASS_SOHO = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Soho"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Spiciness
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPICINESS.<p>
     * 
     */
    public static final OWLClass CLASS_SPICINESS = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Spiciness"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPICYPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_SPICYPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyPizzaEquivalent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPICYPIZZAEQUIVALENT.<p>
     * 
     */
    public static final OWLClass CLASS_SPICYPIZZAEQUIVALENT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyPizzaEquivalent"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPICYTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SPICYTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SpicyTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SpinachTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPINACHTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SPINACHTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SpinachTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SultanaTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SULTANATOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SULTANATOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SultanaTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SundriedTomatoTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUNDRIEDTOMATOTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SUNDRIEDTOMATOTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SundriedTomatoTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#SweetPepperTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SWEETPEPPERTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_SWEETPEPPERTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#SweetPepperTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ThinAndCrispyBase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THINANDCRISPYBASE.<p>
     * 
     */
    public static final OWLClass CLASS_THINANDCRISPYBASE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ThinAndCrispyBase"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ThinAndCrispyPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THINANDCRISPYPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_THINANDCRISPYPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ThinAndCrispyPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#TobascoPepperSauce
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TOBASCOPEPPERSAUCETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_TOBASCOPEPPERSAUCETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#TobascoPepperSauce"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#TomatoTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TOMATOTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_TOMATOTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#TomatoTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#UnclosedPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UNCLOSEDPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_UNCLOSEDPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#UnclosedPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#ValuePartition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VALUEPARTITION.<p>
     * 
     */
    public static final OWLClass CLASS_VALUEPARTITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#ValuePartition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETABLETOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETABLETOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizza
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETARIANPIZZA.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETARIANPIZZA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizza"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizzaEquivalent1
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETARIANPIZZA1.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETARIANPIZZA1 = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizzaEquivalent1"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizzaEquivalent2
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETARIANPIZZA2.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETARIANPIZZA2 = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianPizzaEquivalent2"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianTopping
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VEGETARIANTOPPING.<p>
     * 
     */
    public static final OWLClass CLASS_VEGETARIANTOPPING = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetarianTopping"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Veneziana
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VENEZIANA.<p>
     * 
     */
    public static final OWLClass CLASS_VENEZIANA = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Veneziana"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasBase
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBASE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBASE = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasBase"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasCountryOfOrigin
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCOUNTRYOFORIGIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCOUNTRYOFORIGIN = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasCountryOfOrigin"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasIngredient
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINGREDIENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINGREDIENT = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasIngredient"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasSpiciness
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSPICINESS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSPICINESS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasSpiciness"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasTopping
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTOPPING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTOPPING = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasTopping"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISBASEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISBASEOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#isIngredientOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINGREDIENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINGREDIENTOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#isIngredientOf"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#isToppingOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISTOPPINGOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISTOPPINGOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#isToppingOf"));


}
